---
# Installs Docker

  - name: Add Docker GPG key
    sudo: yes
    apt_key: url=https://get.docker.io/gpg state=present

  - name: Add Docker repository
    sudo: yes
    apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present update_cache=yes

  - name: Install Docker
    sudo: yes
    apt: pkg=lxc-docker

