---
# Installs Docker

  - name: Add Docker GPG key
    sudo: yes
    apt_key: url=https://get.docker.io/gpg state=present

  - name: Add Docker repository
    sudo: yes
    apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present update_cache=yes

  - name: Install Docker
    sudo: yes
    apt: pkg=lxc-docker

  - name: Add user to docker group (avoids sudo being necessary)
    sudo: yes
    command: usermod -a -G docker $ansible_user_id
