---
# Install Oracle Java

  - name: Add Oracle Java ppa
    sudo: yes
    apt_repository: repo=ppa:webupd8team/java state=present update-cache=yes

  - name: Autoaccept Oracle Java license
    sudo: yes
    shell: echo 'oracle-java7-installer shared/accepted-oracle-license-v1-1 select true' | debconf-set-selections
  
  - name: Install Oracle Java
    sudo: yes
    apt: pkg={{ item }} state=latest update-cache=yes
    with_items:
      - oracle-java7-installer
      - oracle-java7-set-default
